SCREEN_W = 800
SCREEN_H = 600

TITLE = 'Breakout'

START_TEXT = 'START'
HIGH_SCORE_TEXT = 'HIGH SCORES'
GAME_OVER_TEXT = 'GAME OVER'
PAUSE_TEXT = 'PAUSED'
PAUSE_SPACE_TEXT = 'Press space to resume'
GAME_OVER_SPACE_TEXT = 'Press space to go to start'
SCORE_TEXT = 'SCORE:'

BALL_SPEED = 150
PADDLE_SPEED = 500